# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxMemoryManagement' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxCocoa',    '~> 3.0'
  pod 'RxSwift',    '~> 3.0'
  # Pods for RxMemoryManagement

  target 'RxMemoryManagementTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxMemoryManagementUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
