# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlertViewQueue' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlertViewQueue
  pod 'Swinject', '~> 2.1.0'
  pod 'RxCocoa',    '~> 3.0'
  pod 'RxSwift',    '~> 3.0'

  target 'AlertViewQueueTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlertViewQueueUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
